### ISSUE TITLE
Failed to create logical device (GeForce GTX 1060 6GB)

### ISSUE THREAD

**Issue by SamuelTallet** [konstatoivanen/PKRenderer#1]
Hello,

When I run PKRenderer.exe (version 1.0), I get this critical error:

```
 Selected Physical Device 'NVIDIA GeForce GTX 1060' from '2' physical devices.
   Vendor: 4318
   Device: 7200
   Driver: 2143666176
   API VER: 1.2

[...]

Device Extension: VK_NVX_multiview_per_view_attributes (C:\WINDOWS\System32\DriverStore\FileRepository\nvamig.inf_amd64_2845149b505e4dbf\.\nvoglv64.dll) version 0.0.1
vkCreateDevice:  Failed to create device chain.
Failed to create logical device!
```

**Comment by konstatoivanen** [comment]
Hey,

Added a new release that has proper validation of physical device features & api version. 
If you still experience this issue it is likely that your driver version doesn't support the multiviewport feature or Vulkan 1.2.

**Comment by SamuelTallet** [comment]
Thanks, I will try the new release 😉

By the way, what are the required Vulkan extensions to run PKRenderer?

I saw that support of DirectX12 is planned. Do you already know the software and hardware requirements for this backend?

**Comment by konstatoivanen** [comment]
I added the required features & extensions to readme.md

I haven't researched DX12 yet. Currently my priority is to validate that the Vulkan API RHI covers my use cases & is logically robust enough, as well as optimize the implementation & remove some hacks I did when porting this from my old OpenGL project (for example, projection matrix z range is currently remapped from -1, 1 to 0 , 1 in vertex programs).

**Comment by SamuelTallet** [comment]
Thanks for the additions in README.md.

**Comment by SamuelTallet** [comment]
Indeed, my graphics card isn't supported.

**Comment by konstatoivanen** [comment]
That is sad to hear. Did you manage to find which feature is not supported? I know I'm not logging this information at the moment as it is not trivially stringifiable.

**Comment by SamuelTallet** [comment]
Anyway, thanks for your support. I don't know exactly which Vulkan features/extensions I miss. I could know them with [GLView](https://www.realtech-vr.com/home/glview)...

I will either buy a new laptop with a more powerful graphics card, either use a remote desktop like the one provided by [Shadow](https://shadow.tech/).
